<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../CryptexSharp.Domain/CryptexSharp.Domain.csproj" />
    <ProjectReference Include="../CryptexSharp.Infrastructure/CryptexSharp.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.5.1" />
    <PackageReference Include="Sodium.Core" Version="1.3.5" />
  </ItemGroup>

</Project>
