<!--
Copyright (c) 2025 vinici.us.com. All Rights Reserved.
Licensed under the MIT license.
-->

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../CryptexSharp.Domain/CryptexSharp.Domain.csproj" />
    <ProjectReference Include="../CryptexSharp.Service/CryptexSharp.Core.csproj" />
  </ItemGroup>

</Project>